#!/bin/bash
cd /checkpoint/ndecao/wikipedia
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py afwiki-20191001-pages-articles-multistream.xml.bz2 -o af --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py anwiki-20191001-pages-articles-multistream.xml.bz2 -o an --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py arwiki-20191001-pages-articles-multistream.xml.bz2 -o ar --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py astwiki-20191001-pages-articles-multistream.xml.bz2 -o ast --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py azwiki-20191001-pages-articles-multistream.xml.bz2 -o az --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py azbwiki-20191001-pages-articles-multistream.xml.bz2 -o azb --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bawiki-20191001-pages-articles-multistream.xml.bz2 -o ba --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py barwiki-20191001-pages-articles-multistream.xml.bz2 -o bar --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bewiki-20191001-pages-articles-multistream.xml.bz2 -o be --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bgwiki-20191001-pages-articles-multistream.xml.bz2 -o bg --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bnwiki-20191001-pages-articles-multistream.xml.bz2 -o bn --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bpywiki-20191001-pages-articles-multistream.xml.bz2 -o bpy --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py brwiki-20191001-pages-articles-multistream.xml.bz2 -o br --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bswiki-20191001-pages-articles-multistream.xml.bz2 -o bs --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cawiki-20191001-pages-articles-multistream.xml.bz2 -o ca --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cewiki-20191001-pages-articles-multistream.xml.bz2 -o ce --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cebwiki-20191001-pages-articles-multistream.xml.bz2 -o ceb --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cswiki-20191001-pages-articles-multistream.xml.bz2 -o cs --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cvwiki-20191001-pages-articles-multistream.xml.bz2 -o cv --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cywiki-20191001-pages-articles-multistream.xml.bz2 -o cy --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py dawiki-20191001-pages-articles-multistream.xml.bz2 -o da --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py dewiki-20191001-pages-articles-multistream.xml.bz2 -o de --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py elwiki-20191001-pages-articles-multistream.xml.bz2 -o el --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py enwiki-20191001-pages-articles-multistream.xml.bz2 -o en --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py eswiki-20191001-pages-articles-multistream.xml.bz2 -o es --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py etwiki-20191001-pages-articles-multistream.xml.bz2 -o et --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py euwiki-20191001-pages-articles-multistream.xml.bz2 -o eu --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py fawiki-20191001-pages-articles-multistream.xml.bz2 -o fa --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py fiwiki-20191001-pages-articles-multistream.xml.bz2 -o fi --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py filwiki-20191001-pages-articles-multistream.xml.bz2 -o fil --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py frwiki-20191001-pages-articles-multistream.xml.bz2 -o fr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py fywiki-20191001-pages-articles-multistream.xml.bz2 -o fy --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py gawiki-20191001-pages-articles-multistream.xml.bz2 -o ga --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py glwiki-20191001-pages-articles-multistream.xml.bz2 -o gl --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py guwiki-20191001-pages-articles-multistream.xml.bz2 -o gu --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py hiwiki-20191001-pages-articles-multistream.xml.bz2 -o hi --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py hrwiki-20191001-pages-articles-multistream.xml.bz2 -o hr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py htwiki-20191001-pages-articles-multistream.xml.bz2 -o ht --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py huwiki-20191001-pages-articles-multistream.xml.bz2 -o hu --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py hywiki-20191001-pages-articles-multistream.xml.bz2 -o hy --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py idwiki-20191001-pages-articles-multistream.xml.bz2 -o id --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py iowiki-20191001-pages-articles-multistream.xml.bz2 -o io --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py iswiki-20191001-pages-articles-multistream.xml.bz2 -o is --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py itwiki-20191001-pages-articles-multistream.xml.bz2 -o it --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py iwwiki-20191001-pages-articles-multistream.xml.bz2 -o iw --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py jawiki-20191001-pages-articles-multistream.xml.bz2 -o ja --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py jvwiki-20191001-pages-articles-multistream.xml.bz2 -o jv --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py kawiki-20191001-pages-articles-multistream.xml.bz2 -o ka --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py kkwiki-20191001-pages-articles-multistream.xml.bz2 -o kk --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py knwiki-20191001-pages-articles-multistream.xml.bz2 -o kn --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py kowiki-20191001-pages-articles-multistream.xml.bz2 -o ko --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py kywiki-20191001-pages-articles-multistream.xml.bz2 -o ky --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py lawiki-20191001-pages-articles-multistream.xml.bz2 -o la --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py lahwiki-20191001-pages-articles-multistream.xml.bz2 -o lah --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py lbwiki-20191001-pages-articles-multistream.xml.bz2 -o lb --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py lmowiki-20191001-pages-articles-multistream.xml.bz2 -o lmo --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ltwiki-20191001-pages-articles-multistream.xml.bz2 -o lt --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py lvwiki-20191001-pages-articles-multistream.xml.bz2 -o lv --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mgwiki-20191001-pages-articles-multistream.xml.bz2 -o mg --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py minwiki-20191001-pages-articles-multistream.xml.bz2 -o min --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mkwiki-20191001-pages-articles-multistream.xml.bz2 -o mk --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mlwiki-20191001-pages-articles-multistream.xml.bz2 -o ml --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mnwiki-20191001-pages-articles-multistream.xml.bz2 -o mn --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mrwiki-20191001-pages-articles-multistream.xml.bz2 -o mr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mswiki-20191001-pages-articles-multistream.xml.bz2 -o ms --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py mywiki-20191001-pages-articles-multistream.xml.bz2 -o my --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ndswiki-20191001-pages-articles-multistream.xml.bz2 -o nds --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py newiki-20191001-pages-articles-multistream.xml.bz2 -o ne --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py newwiki-20191001-pages-articles-multistream.xml.bz2 -o new --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py nlwiki-20191001-pages-articles-multistream.xml.bz2 -o nl --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py nnwiki-20191001-pages-articles-multistream.xml.bz2 -o nn --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py nowiki-20191001-pages-articles-multistream.xml.bz2 -o no --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ocwiki-20191001-pages-articles-multistream.xml.bz2 -o oc --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py pawiki-20191001-pages-articles-multistream.xml.bz2 -o pa --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py plwiki-20191001-pages-articles-multistream.xml.bz2 -o pl --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py pmswiki-20191001-pages-articles-multistream.xml.bz2 -o pms --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ptwiki-20191001-pages-articles-multistream.xml.bz2 -o pt --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py rowiki-20191001-pages-articles-multistream.xml.bz2 -o ro --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ruwiki-20191001-pages-articles-multistream.xml.bz2 -o ru --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py scnwiki-20191001-pages-articles-multistream.xml.bz2 -o scn --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py scowiki-20191001-pages-articles-multistream.xml.bz2 -o sco --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py skwiki-20191001-pages-articles-multistream.xml.bz2 -o sk --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py slwiki-20191001-pages-articles-multistream.xml.bz2 -o sl --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py sqwiki-20191001-pages-articles-multistream.xml.bz2 -o sq --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py srwiki-20191001-pages-articles-multistream.xml.bz2 -o sr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py sr-Latnwiki-20191001-pages-articles-multistream.xml.bz2 -o sr-Latn --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py suwiki-20191001-pages-articles-multistream.xml.bz2 -o su --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py svwiki-20191001-pages-articles-multistream.xml.bz2 -o sv --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py swwiki-20191001-pages-articles-multistream.xml.bz2 -o sw --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py tawiki-20191001-pages-articles-multistream.xml.bz2 -o ta --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py tewiki-20191001-pages-articles-multistream.xml.bz2 -o te --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py tgwiki-20191001-pages-articles-multistream.xml.bz2 -o tg --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py thwiki-20191001-pages-articles-multistream.xml.bz2 -o th --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py trwiki-20191001-pages-articles-multistream.xml.bz2 -o tr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ttwiki-20191001-pages-articles-multistream.xml.bz2 -o tt --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ukwiki-20191001-pages-articles-multistream.xml.bz2 -o uk --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py urwiki-20191001-pages-articles-multistream.xml.bz2 -o ur --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py uzwiki-20191001-pages-articles-multistream.xml.bz2 -o uz --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py viwiki-20191001-pages-articles-multistream.xml.bz2 -o vi --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py vowiki-20191001-pages-articles-multistream.xml.bz2 -o vo --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py warwiki-20191001-pages-articles-multistream.xml.bz2 -o war --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py yowiki-20191001-pages-articles-multistream.xml.bz2 -o yo --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py zhwiki-20191001-pages-articles-multistream.xml.bz2 -o zh --links --section_hierarchy --lists --sections
