#!/bin/bash
cd /checkpoint/ndecao/wikinews
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py arwikinews-20191001-pages-articles-multistream.xml.bz2 -o ar --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bgwikinews-20191001-pages-articles-multistream.xml.bz2 -o bg --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py bswikinews-20191001-pages-articles-multistream.xml.bz2 -o bs --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cawikinews-20191001-pages-articles-multistream.xml.bz2 -o ca --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py cswikinews-20191001-pages-articles-multistream.xml.bz2 -o cs --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py dewikinews-20191001-pages-articles-multistream.xml.bz2 -o de --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py elwikinews-20191001-pages-articles-multistream.xml.bz2 -o el --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py enwikinews-20191001-pages-articles-multistream.xml.bz2 -o en --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py eowikinews-20191001-pages-articles-multistream.xml.bz2 -o eo --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py eswikinews-20191001-pages-articles-multistream.xml.bz2 -o es --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py fawikinews-20191001-pages-articles-multistream.xml.bz2 -o fa --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py fiwikinews-20191001-pages-articles-multistream.xml.bz2 -o fi --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py frwikinews-20191001-pages-articles-multistream.xml.bz2 -o fr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py hewikinews-20191001-pages-articles-multistream.xml.bz2 -o he --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py huwikinews-20191001-pages-articles-multistream.xml.bz2 -o hu --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py itwikinews-20191001-pages-articles-multistream.xml.bz2 -o it --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py jawikinews-20191001-pages-articles-multistream.xml.bz2 -o ja --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py kowikinews-20191001-pages-articles-multistream.xml.bz2 -o ko --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py nlwikinews-20191001-pages-articles-multistream.xml.bz2 -o nl --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py nowikinews-20191001-pages-articles-multistream.xml.bz2 -o no --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py plwikinews-20191001-pages-articles-multistream.xml.bz2 -o pl --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ptwikinews-20191001-pages-articles-multistream.xml.bz2 -o pt --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py rowikinews-20191001-pages-articles-multistream.xml.bz2 -o ro --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ruwikinews-20191001-pages-articles-multistream.xml.bz2 -o ru --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py sdwikinews-20191001-pages-articles-multistream.xml.bz2 -o sd --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py sqwikinews-20191001-pages-articles-multistream.xml.bz2 -o sq --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py srwikinews-20191001-pages-articles-multistream.xml.bz2 -o sr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py svwikinews-20191001-pages-articles-multistream.xml.bz2 -o sv --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py tawikinews-20191001-pages-articles-multistream.xml.bz2 -o ta --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py thwikinews-20191001-pages-articles-multistream.xml.bz2 -o th --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py trwikinews-20191001-pages-articles-multistream.xml.bz2 -o tr --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py ukwikinews-20191001-pages-articles-multistream.xml.bz2 -o uk --links --section_hierarchy --lists --sections
python /private/home/ndecao/mGENRE/wikiextractor/WikiExtractor.py zhwikinews-20191001-pages-articles-multistream.xml.bz2 -o zh --links --section_hierarchy --lists --sections
